AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 300

Metrics/MethodLength:
  Max: 60

Metrics/BlockLength:
  Max: 150

Metrics/ParameterLists:
  Max: 15
