# frozen_string_literal: true

module Upi
  # Percent-encoding shared by every URI the gem builds or reads.
  #
  # The specification is explicit that this is RFC 3986 section 2.1
  # percent-encoding, which makes a space `%20`. `+` means a literal plus here,
  # not a space, however tempting the form-encoding habit is.
  module Encoding
    # RFC 3986 unreserved set. Everything else is percent-encoded.
    STRICT_UNSAFE = /[^A-Za-z0-9\-._~]/.freeze

    # Leaves characters that are legal inside a query value untouched, so a
    # redirect URL stays readable as `https://host/path` the way the NPCI
    # examples show it. `&`, `#`, `%`, `+` and space are still escaped, so a
    # value can never break out and forge another parameter.
    LENIENT_UNSAFE = %r{[^A-Za-z0-9\-._~:/?=@!$'()*,;]}.freeze

    PERCENT_TRIPLET = /%([0-9A-Fa-f]{2})/.freeze

    module_function

    def encode(value, lenient: false)
      pattern = lenient ? LENIENT_UNSAFE : STRICT_UNSAFE
      value.to_s.gsub(pattern) { |char| char.bytes.map { |byte| format('%%%02X', byte) }.join }
    end

    # @param plus_as_space [Boolean] treat `+` as a space. Off-spec, but QR codes
    #   in the wild were generated by tools that used form encoding, so an
    #   inbound parser that refuses to cope with them is not much use.
    def decode(value, plus_as_space: false)
      text = value.to_s
      text = text.tr('+', ' ') if plus_as_space
      text.gsub(PERCENT_TRIPLET) { Regexp.last_match(1).hex.chr }
          .force_encoding(::Encoding::UTF_8)
    end
  end
end
