module Upi
  class Generator
    @no_url_parse: bool
    @params: Hash[Symbol, String]

    attr_reader params: Hash[Symbol, String]

    def generate_qr: -> String

    def upi_content: -> String

    private

    def generate_transaction: -> Hash[Symbol, String]
  end
end
